# Generated by Django 4.2.3 on 2023-07-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gttour', '0002_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
