# Generated by Django 4.2.3 on 2023-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=1)),
                ('family', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
