# Generated by Django 4.2.3 on 2023-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='family',
            field=models.BooleanField(default=False),
        ),
    ]
