# Generated by Django 4.2.3 on 2023-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitting', '0002_alter_place_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('average_vector', models.TextField()),
                ('cluster', models.IntegerField()),
            ],
        ),
    ]
