# Generated by Django 4.2.3 on 2023-07-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
