# Generated by Django 4.2.3 on 2023-07-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_survey_area_1_alter_survey_area_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='family',
            field=models.BooleanField(default=False),
        ),
    ]
